contentlayer:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'contentlayer.config.ts'
              - 'config/contentlayer/**'

dependencies:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'pnpm-lock.yaml'

documentation:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'content/**/*'

eslint:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'eslint.*'

tsconfig:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - 'tsconfig.json'

v2:
  - any:
      - head-branch: [ '^wip/v2$' ]

workflows:
  - any:
      - changed-files:
          - any-glob-to-any-file:
              - '.github/workflows/**/*'
